version: '3'

services:
  geminiprochat:
    build: .
    container_name: geminiprochat
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=https://app.netlify.com/sites/glistening-muffin-b2a95a/overview
      # - HTTPS_PROXY=YOUR_HTTPS_PROXY
      - API_BASE_URL=https://glistening-muffin-b2a95a.netlify.app
      # - HEAD_SCRIPTS=YOUR_HEAD_SCRIPTS
      # - PUBLIC_SECRET_KEY=YOUR_SECRET_KEY
      # - SITE_PASSWORD=YOUR_SITE_PASSWORD
      # - OPENAI_API_MODEL=YOUR_OPENAI_API_MODEL

